/*
 * Project name:
     Tetris.vtft
 * Generated by:
     Visual TFT
 * Date of creation
     22-Aug-14
 * Time of creation
     07:51:39
 * Test configuration:
     MCU:             TM4C129XNCZAD
     Dev.Board:       mikromedia_5_for_TIVA
                      http://www.mikroe.com/mikromedia/5/tiva/
     Oscillator:      120000000 Hz
     SW:              mikroC PRO for ARM
                      http://www.mikroe.com/mikroc/arm/
 */

#include "Tetris_objects.h"
#include "game.h"                      
#include "tetris_game.h"
#include "graphics.h"

void main()
{
    Start_TP();
    Initialize_Game();

    while (1)
    {
        Check_TP();
        Update_Game();
    }
}
